services:
  anthropic-proxy:
    build: .
    container_name: anthropic-proxy
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment: 
      # === Core Configuration ===
      - DEBUG=${DEBUG:-true}
      # - SERVER_API_KEY=${SERVER_API_KEY}
      # - UPSTREAM_BASE=${UPSTREAM_BASE:-https://api.z.ai/api/anthropic}
      # - OPENAI_UPSTREAM_BASE=${OPENAI_UPSTREAM_BASE:-https://api.z.ai/api/coding/paas/v4}
      
      # === Request Forwarding ===
      # - FORWARD_CLIENT_KEY=${FORWARD_CLIENT_KEY:-true}
      # - FORWARD_COUNT_TO_UPSTREAM=${FORWARD_COUNT_TO_UPSTREAM:-true}
      
      # === Anthropic Beta Features ===
      # - FORCE_ANTHROPIC_BETA=${FORCE_ANTHROPIC_BETA:-false}
      # - DEFAULT_ANTHROPIC_BETA=${DEFAULT_ANTHROPIC_BETA:-prompt-caching-2024-07-31}
      
      # === Model Configuration ===
      # - MODEL_MAP_JSON=${MODEL_MAP_JSON:-{}}
      - AUTOTEXT_MODEL=${AUTOTEXT_MODEL:-glm-4.6}
      - AUTOVISION_MODEL=${AUTOVISION_MODEL:-glm-4.5v}
      # - TEXT_ENDPOINT_PREFERENCE=${TEXT_ENDPOINT_PREFERENCE:-auto}
      
      # === Token Counting ===
      # - COUNT_SHAPE_COMPAT=${COUNT_SHAPE_COMPAT:-true}
      # - MIN_CACHEABLE_TOKENS=${MIN_CACHEABLE_TOKENS:-1024}
      # - SCALE_COUNT_TOKENS_FOR_VISION=${SCALE_COUNT_TOKENS_FOR_VISION:-true}
      
      # === Token Scaling Configuration ===
      # - ANTHROPIC_EXPECTED_TOKENS=${ANTHROPIC_EXPECTED_TOKENS:-200000}
      - OPENAI_EXPECTED_TOKENS=200000
      - REAL_TEXT_MODEL_TOKENS=200000
      - REAL_VISION_MODEL_TOKENS=${REAL_VISION_MODEL_TOKENS:-65536}
      
      # === Cache Configuration ===
      # - CACHE_DEFAULT_TTL_SECONDS=${CACHE_DEFAULT_TTL_SECONDS:-300}
      # - CACHE_1H_TTL_SECONDS=${CACHE_1H_TTL_SECONDS:-3600}
    volumes:
      - ./logs:/app/logs
      - ./cache:/app/cache
    networks:
      - anthropic-proxy-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  anthropic-proxy-network:
    driver: bridge

volumes:
  logs:
    driver: local
  cache:
    driver: local